# Generated by Django 4.1.7 on 2023-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=64, null=True)),
                ("icon_uri", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "manifest_uri",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=128, null=True)),
                ("focus", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("extra_text", models.JSONField(blank=True, null=True)),
                (
                    "certificate_uri",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("drm", models.JSONField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("license_servers", models.JSONField(blank=True, null=True)),
                ("license_request_headers", models.JSONField(blank=True, null=True)),
                (
                    "request_filter",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "response_filter",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                ("clear_keys", models.JSONField(blank=True, null=True)),
                ("extra_config", models.JSONField(blank=True, null=True)),
                ("ad_tag_uri", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "ima_video_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "ima_asset_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "ima_content_src_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "media_playlist_full_mime_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("stored_progress", models.IntegerField()),
                (
                    "stored_content",
                    models.JSONField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
